permalink: /blog/:year/:month/:title.html
include: ['.htaccess']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
markdown: kramdown
highlights: pygments
url: "http://127.0.0.1:40000"
cdn_url: 7u2t01.com1.z0.glb.clouddn.com
lsi: false
safe: true
timezone: Asia/Shanghai

gems: [jekyll-paginate]
paginate: 8
paginate_path: "page:num"
enable_coderay: true

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6


JB :
  IMAGE_PATH : http://127.0.0.1:40000/images

# presonal config
#domain: http://coolshell.info
title: Lee24
description: When all else is lost the future still remains.
author: chenglee
email: li.zicheng@qq.com
github: Lee24

config:
  js_dir:
  img_dir:
  css_dir:
