permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author:
  name: Lee24
  email: li.zicheng@qq.com

rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/logo.png
favicon: /public/img/logo.png


# 主题设置，自动激活某个标签
active: 杂谈


# 中文本地化
locals:
  tags: 知识
  about: 关于
  newest: 最新文章
  archive: 归档

# 配置项目
gems: [jekyll-paginate]
